https://www.kaggle.com/code/ryanholbrook/binary-classification/tutorial

电离层数据，目标是判断是否有飞行物

首先要解决从csv读取文件的问题


In [2]:
# 穿插一些tf.data相关的内容
import tensorflow as tf
import numpy as np

tf.print(tf.__version__)
tf.print(tf.config.list_physical_devices('GPU'))

np_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
dataset = tf.data.Dataset.from_tensor_slices(np_arr)

print(dataset)

print(dataset.as_numpy_iterator())

2.10.0
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
<TensorSliceDataset element_spec=TensorSpec(shape=(3,), dtype=tf.int32, name=None)>


In [11]:

import tensorflow as tf

column_names = ["v" + str(i) for i in range(1, 36)]
feature_names = column_names[:-1]
label_name = column_names[-1]

dataset = tf.data.experimental.make_csv_dataset(
    '../dataset/binary_classification/lonosphere/ionosphere.data',
    batch_size=10,
    column_names=column_names,
    label_name=label_name,
    na_value="?",
    num_epochs=1,
    ignore_errors=True)

print(type(dataset))
print(len(list(dataset)))

features, labels = next(iter(dataset))

print(features)
print('-----------')
print(labels)


<class 'tensorflow.python.data.ops.dataset_ops.PrefetchDataset'>
35
OrderedDict([('v1', <tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])>), ('v2', <tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])>), ('v3', <tf.Tensor: shape=(10,), dtype=float32, numpy=
array([1.     , 0.42708, 0.     , 0.88116, 0.     , 1.     , 0.67065,
       0.88179, 0.96071, 0.95659], dtype=float32)>), ('v4', <tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 0.11765, -0.5    ,  0.     ,  0.27475,  0.     ,  0.03529,
        0.02528,  0.43491,  0.07088,  0.08143], dtype=float32)>), ('v5', <tf.Tensor: shape=(10,), dtype=float32, numpy=
array([1.     , 0.     , 0.     , 0.72125, 1.     , 1.     , 0.66626,
       0.59573, 1.     , 0.97487], dtype=float32)>), ('v6', <tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 0.23529,  0.     ,  0.     ,  0.42881, -1.     ,  0.18281,
        0.05031,  0.77655,  0.04296, -0.05667], dtype=float32)>), ('v7', 

数据加载完毕，开始训练


In [16]:
from keras import layers
from keras import models

batch_size = 10
test_size = batch_size * 2

test_data = dataset.take(test_size).batch(batch_size)
train_data = dataset.skip(test_size).shuffle(35, )

for x in train_data:
    print(x)

# model = models.Sequential()
# model.add(layers.Dense(16, activation='relu', input_shape=(34,)))
# model.add(layers.Dense(16, activation='relu'))
# model.add(layers.Dense(1, activation='sigmoid'))
#
# model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
# history = model.fit(train_data, validation_data=test_data, epochs=30)
#


(OrderedDict([('v1', <tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1])>), ('v2', <tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])>), ('v3', <tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-1.     ,  1.     ,  1.     ,  0.68148,  1.     ,  0.95882,
        0.7983 ,  0.7087 ,  0.94649,  0.94052], dtype=float32)>), ('v4', <tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-1.     , -1.     , -0.06604,  0.1037 ,  0.51515,  0.10129,
        0.09417, -0.24783,  0.00892, -0.01531], dtype=float32)>), ('v5', <tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 1.     , -1.     ,  1.     ,  0.77037,  0.45455,  1.     ,
        0.78129,  0.64348,  0.97287,  0.9417 ], dtype=float32)>), ('v6', <tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-1.     ,  1.     ,  0.62937,  0.03457,  0.33333, -0.01918,
        0.20656,  0.04348, -0.0026 ,  0.01001], dtype=float32)>), ('v7', <tf.Tensor: shape=(10,), dtype=float32, numpy=


In [18]:

import tensorflow as tf
tf.random.uniform([4, 10])

dataset1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([4, 10]))
dataset1.element_spec

for z in dataset1:
  print(z.numpy())

dataset2 = tf.data.Dataset.from_tensor_slices(
   (tf.random.uniform([4]),
    tf.random.uniform([4, 100], maxval=100, dtype=tf.int32)))

dataset2.element_spec

dataset3 = tf.data.Dataset.zip((dataset1, dataset2))

dataset3.element_spec

dataset4 = tf.data.Dataset.from_tensors(tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4]))

dataset4.element_spec

dataset1 = tf.data.Dataset.from_tensor_slices(
    tf.random.uniform([4, 10], minval=1, maxval=10, dtype=tf.int32))



dataset2 = tf.data.Dataset.from_tensor_slices(
   (tf.random.uniform([4]),
    tf.random.uniform([4, 100], maxval=100, dtype=tf.int32)))

dataset2

dataset3 = tf.data.Dataset.zip((dataset1, dataset2))

dataset3

for a, (b,c) in dataset3:
  print('shapes: {a.shape}, {b.shape}, {c.shape}'.format(a=a, b=b, c=c))


[0.30614161 0.28652728 0.22725487 0.23066235 0.2799244  0.48344684
 0.8978727  0.6421536  0.3053658  0.89870965]
[0.9361515  0.037287   0.44426787 0.7222241  0.82848585 0.3850969
 0.410159   0.45492935 0.59230506 0.20001721]
[0.17511213 0.530607   0.35571337 0.729589   0.48880994 0.15005589
 0.15979087 0.04434168 0.6370846  0.4304061 ]
[0.52708817 0.98185074 0.01509368 0.19671988 0.94576144 0.15066934
 0.66056716 0.87374675 0.24713957 0.42398775]
shapes: (10,), (), (100,)
shapes: (10,), (), (100,)
shapes: (10,), (), (100,)
shapes: (10,), (), (100,)


In [23]:
import tensorflow as tf

def count(stop):
  i = 0
  while i<stop:
    yield i
    i += 1

# for n in count(5):
#   print(n)

ds_counter = tf.data.Dataset.from_generator(count, args=[25], output_types=tf.int32, output_shapes = (), )

# for x in ds_counter:
#     print(x.numpy())

for count_batch in ds_counter.repeat().batch(10).take(10):
  print(count_batch.numpy())

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24  0  1  2  3  4]
[ 5  6  7  8  9 10 11 12 13 14]
[15 16 17 18 19 20 21 22 23 24]
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24  0  1  2  3  4]
[ 5  6  7  8  9 10 11 12 13 14]
[15 16 17 18 19 20 21 22 23 24]


In [27]:
import tensorflow as tf
import numpy as np

def gen_series():
  i = 0
  while True:
    size = np.random.randint(0, 10)
    yield i, np.random.normal(size=(size,))
    i += 1

# for i, series in gen_series():
#   print(i, ":", str(series))
#   if i > 5:
#     break

ds_series = tf.data.Dataset.from_generator(
    gen_series,
    output_types=(tf.int32, tf.float32),
    output_shapes=((), (None,)))

# ds_series
ds_series_batch = ds_series.shuffle(20).padded_batch(10)

ids, sequence_batch = next(iter(ds_series_batch))
print(ids.numpy())
print()
print(sequence_batch.numpy())

[ 0  1 12 10 19  3 23 13  2 26]

[[-0.10428519  1.1082284   0.38469735  0.23174408  1.4029541   0.91373646
  -0.3295687   0.          0.        ]
 [ 0.6861336   0.3151567  -2.02125     0.15125655 -1.8165655  -0.39504477
   0.          0.          0.        ]
 [-0.3405827  -0.5760708  -0.6873614  -0.6906055   0.6958224   0.32335967
   0.          0.          0.        ]
 [ 2.3854024   1.197426    0.32684743 -0.2673078   0.          0.
   0.          0.          0.        ]
 [-1.2343459   0.16132478  1.3915262   0.          0.          0.
   0.          0.          0.        ]
 [ 0.09499443 -0.15158436  0.52194524  0.          0.          0.
   0.          0.          0.        ]
 [ 1.0864956   1.3420986   2.0355258   2.1047955   0.          0.
   0.          0.          0.        ]
 [-0.09597915  0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [-0.2957503   1.4990206  -2.3677711   0.826945    0.7715354  -1.0393113
   0.3037166  -1.2994471   0.3

In [1]:
import tensorflow as tf
import numpy as np

flowers = tf.keras.utils.get_file(
    'flower_photos',
    'https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz',
    untar=True)

img_gen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255, rotation_range=20)
images, labels = next(img_gen.flow_from_directory(flowers))
print(images.dtype, images.shape)
print(labels.dtype, labels.shape)
ds = tf.data.Dataset.from_generator(
    lambda: img_gen.flow_from_directory(flowers),
    output_types=(tf.float32, tf.float32),
    output_shapes=([32,256,256,3], [32,5])
)

ds.element_spec

for images, labels in ds.take(1):
  print('images.shape: ', images.shape)


Found 3670 images belonging to 5 classes.


NameError: name 'scipy' is not defined