tf.data API引入了tf.data.Dataset抽象表示一个元素序列

## 基本机制

`tf.data.Dataset.from_tensors()` 或者 `tf.data.Dataset.from_tensor_slices()`

基本用法

In [31]:
import tensorflow as tf


def dis(ds):
    for elem in ds:
        print(elem.numpy())

dataset = tf.data.Dataset.from_tensor_slices([8, 3, 0, 8, 2, 1])

print(dataset)

print('---------------------------------------')

for elem in dataset:
    print(elem.numpy())

print('---------------------------------------')
print(dataset.reduce(0, lambda state, value: state + value).numpy())

print('--------------------------------------')
dataset1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([4, 10]))

print(dataset1.element_spec)

print('--------------------------------------')

dataset2 = tf.data.Dataset.from_tensor_slices(
   (tf.random.uniform([4]),
    tf.random.uniform([4, 100], maxval=100, dtype=tf.int32)))

print(dataset2.element_spec)

print('--------------------------------------')
dataset3= tf.data.Dataset.zip((dataset1, dataset2))
print(dataset3.element_spec)

print('--------------------------------------')
# Dataset containing a sparse tensor.
dataset4 = tf.data.Dataset.from_tensors(tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4]))

print(dataset4.element_spec)

print('--------------------------------------')
dataset1 = tf.data.Dataset.from_tensor_slices(
    tf.random.uniform([4, 10], minval=1, maxval=10, dtype=tf.int32))

print(dataset1)

dis(dataset1)

print('--------------------------------------')

dataset2 = tf.data.Dataset.from_tensor_slices(
   (tf.random.uniform([4]),
    tf.random.uniform([4, 100], maxval=100, dtype=tf.int32)))

print(dataset2)

print('--------------------------------------')

for ds in dataset2:
    print('--------------------------------------')
    dis(ds)

print('--------------------------------------')
dataset3 = tf.data.Dataset.zip((dataset1, dataset2))

print(dataset3)

print('----------------------------------')

for a, (b, c) in dataset3:
    print('shapes: {a.shape}, {b.shape}, {c.shape}'.format(a=a, b=b, c=c))



<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>
---------------------------------------
8
3
0
8
2
1
---------------------------------------
22
--------------------------------------
TensorSpec(shape=(10,), dtype=tf.float32, name=None)
--------------------------------------
(TensorSpec(shape=(), dtype=tf.float32, name=None), TensorSpec(shape=(100,), dtype=tf.int32, name=None))
--------------------------------------
(TensorSpec(shape=(10,), dtype=tf.float32, name=None), (TensorSpec(shape=(), dtype=tf.float32, name=None), TensorSpec(shape=(100,), dtype=tf.int32, name=None)))
--------------------------------------
SparseTensorSpec(TensorShape([3, 4]), tf.int32)
--------------------------------------
<TensorSliceDataset element_spec=TensorSpec(shape=(10,), dtype=tf.int32, name=None)>
[3 4 7 7 9 9 3 3 4 3]
[1 1 7 7 4 7 3 6 6 8]
[2 1 7 4 9 2 3 8 5 6]
[6 8 7 5 5 7 9 1 9 9]
--------------------------------------
<TensorSliceDataset element_spec=(TensorSpec(shap

### 读取输入数据


In [41]:
train, test = tf.keras.datasets.fashion_mnist.load_data()

print(type(train), type(test))

images, label = train
print(len(train))

print(type(images), type(label))

dataset = tf.data.Dataset.from_tensor_slices((images, label))
print(dataset)


<class 'tuple'> <class 'tuple'>
2
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
<TensorSliceDataset element_spec=(TensorSpec(shape=(28, 28), dtype=tf.uint8, name=None), TensorSpec(shape=(), dtype=tf.uint8, name=None))>
